name: Test and Publish Beta

on:
  push:
    branches: [ develop ]

jobs:

  build:
    runs-on: windows-latest

    env:
      Solution_Name: BardMusicPlayer

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: Build with dotnet
      run: dotnet build --configuration Release

    # Unit tests go here.

    - name: Store artifacts
      uses: actions/upload-artifact@v3
      with:
        name: BardMusicPlayer
        path: BardMusicPlayer\bin\Release\net48\*.exe
        if-no-files-found: error
        retention-days: 1

  deploy:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    
      - name: Checkout Downloads
        uses: actions/checkout@v3
        with:
          repository: BardMusicPlayer/Downloads
          ssh-key: ${{ secrets.DEPLOY_KEY_DOWNLOADS }}
      
      - name: Delete old Beta files
        run: |
          rm -f bmp/release/beta/*
          rm -f bmp/updater/release/1/*
      
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: BardMusicPlayer
          path: bmp/release/beta/
      
      # - name: Delete Polly.dll
        # run: rm bmp/release/beta/Polly.dll
        
      # - name: Move Updater.dll
        # run: |
          # mv bmp/release/beta/BardMusicPlayer.Updater.dll bmp/updater/release/1/
          # sha256sum bmp/updater/release/1/BardMusicPlayer.Updater.dll | cut -d" " -f1 > bmp/updater/release/1/BardMusicPlayer.Updater.dll.sha256
          
      # - name: Generate Version Json
        # run: |
          # pushd bmp/release/beta
          # cat <<EOF > version.json
            # {"beta":true,"commit":"${{ github.sha }}","build":"${{ github.run_number }}","entryDll":"BardMusicPlayer.Ui.dll","entryClass":"BardMusicPlayer.Ui.Main","items":[
          # EOF
          # ls | grep -v version.json | awk '{ system("sha256sum "$1) }' | xargs -n 2 sh -c 'echo "{\"load\":true,\"source\":\"$1\",\"destination\":\"$1\",\"sha256\":\"$0\"}," >> version.json'
          # sed -i '$ s/.$//' version.json
          # echo "]}" >> version.json
          # sed -i ':a;$!{N;s/\n//;ba;}' version.json
          # popd
      
      # - name: Regenerate Version List Json
        # run: |
          # pushd bmp/release
          # echo "[" > versionlist.json
          # set -- */; printf "%s\n" "${@%/}" | xargs -n 1 sh -c 'echo "\"$0\"," >> versionlist.json'
          # sed -i '$ s/.$//' versionlist.json
          # echo "]" >> versionlist.json
          # sed -i ':a;$!{N;s/\n//;ba;}' versionlist.json
          # popd
      
      # - name: Commit Downloads
        # run: |
          # git config --global user.email "doot@bardmusicplayer.com"
          # git config --global user.name "Bard Build Bot"
          # git add bmp/updater/release/1/*
          # git add bmp/release/beta/*
          # git add bmp/release/versionlist.json
          # git commit -am"Beta build ${{ github.run_number }} commit ${{ github.sha }}"
          # git push origin HEAD
